debate-timer/debate-timer-fe

src/layout/components/footer/FixedFooterWrapper.tsx, src/layout/components/header/StickyTriSectionHeader.tsx, src/layout/components/main/ContentContanier.tsx, src/main.tsx, src/page/TableSetupPage/TableSetup.tsx, src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx, src/page/TableSetupPage/components/TimerCreationContent/TimerCreationContent.tsx, src/type/type.ts, src/util/formatting.ts
closed #28
before
after
피드백으로 모달 창 전첵 색상을 변경하는 것이 어떻냐는 의견이 있었으나 그보다는 모달의 제목의 색상을 만을 변경하는 것이 보기 좋다고 판단했습니다.
반대
찬성
중립
이제 작전시간을 선택하여 stance가 중립이 된 경우,  select 내부 문자열을 빈 문자열로 변경되게 했습니다.
중립일 경우 disabled 처리 추가
footerButtonWrapper가 하단 내용을 가리는 문제가 있어 layout을 수정하였습니다.
value값이 number인데 이를 브라우저에서 자체적으로 leading zero를 UI상에서 제거하지 않는 것 같습니다. 이를 toString으로 변환하여 강제로 leading zero를 없앴습니다. 
before
after
타임박스를 입력하기 위해 모달을 열었을때 이전 타임박스를 입력했던 값들을 유지해서 초기값으로 세팅되면 좋겠다는 의견이 있었습니다. 
그래서 초기값을 date의 마지막 배열에 있는 값을 props로 받아서 state의 초기값으로 설정하게 변경하였습니다. 
이때 이전 타임박스가 작전시간인 경우에는 연속적으로 설정되는 경우가 드물것으로 가정하여 이전 데이터에서 시간만을 반영하도록 수정하였습니다.
https://github.com/user-attachments/assets/e6e1654b-f3f9-478f-960e-c7f9784d6e09
해당 기능은 테그크가 크다고 판단하여 현재 이슈와 PR에 반영하지 않고 후에 반영해보도록 하겠습니다.
leading zero관련해서 왜 이렇게 설정해야하는지 정확히 알고 싶은데 잘 나오지 않네요. 혹시 …
=> [FIX] 타임 테이블 구성 페이지 피드백 사항 반영

package-lock.json, package.json, src/hooks/useModal.tsx, src/page/TableListPage/TableListPage.test.tsx, src/page/TableListPage/TableListPage.tsx, src/page/TableListPage/components/Modal/DeleteModalButton.tsx, src/page/TableListPage/components/Modal/EditModalButton.tsx, src/page/TableListPage/components/Modal/EditTableButton.tsx, src/page/TableListPage/components/Modal/EditTableModal.tsx, src/page/TableListPage/components/Table/Table.tsx, src/type/type.ts
closed #43
1. Table 컴포넌트에 수정 및 삭제 컴포넌트 추가
```ts
<div className="flex w-full justify-end gap-4 pb-2 lg:pb-0">
<EditModalButton />
<DeleteModalButton name={name} onDelete={onDelete} />
</div>
```
2.  테이블 수정 - EditModalButton 컴포넌트
```ts
import React from 'react';
import { AiOutlineEdit } from 'react-icons/ai';
import { useModal } from '../../../../hooks/useModal';
import EditTableModal from './EditTableModal';
export default function EditModalButton({ name }: { name: string }) {
const { openModal, ModalWrapper } = useModal();
const handleEdit = (e: React.MouseEvent) => {
e.stopPropagation();
openModal();
};
return (
<>
<button
onClick={handleEdit}
className="transform text-lg  duration-200 hover:scale-125 lg:text-2xl"
>
<AiOutlineEdit />
</button>
<ModalWrapper>
<EditTableModal name={name} …
```
=> [FEAT] 테이블 수정 및 삭제 구현

package-lock.json, package.json, src/layout/components/main/ContentContanier.tsx, src/page/TableSetupPage/TableSetup.test.tsx, src/page/TableSetupPage/TableSetup.tsx, src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx, src/page/TableSetupPage/components/DeleteConfirmContent/DeleteConfirmContent.tsx, src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.stories.tsx, src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.tsx
closed #40
타임박스에 수정 및  삭제 UI 추가
- 수정 버튼과 삭제 버튼을 위한 react-icons를 추가
- 수정 버튼과 삭제 버튼의 재사용을 위한 EditDeleteButtons 구현
- DebatePanel의 분기 처리에 따른 컴퍼넌트의 높이를 동일하게 수정
- defaultlayout의 gap 수정
- src/page/TableSetupPage/TableSetup.tsx
- src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
- src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.tsx
- src/layout/components/main/ContentContanier.tsx
- package.json
=> [FEAT] 타임박스에 수정 및 삭제 UI 추가

src/mocks/handlers.tsx, src/type/type.ts
closed #53 
- request.json()의 반환 타입 미정의: MSW에서 request.json()은 기본적으로 Promise<any> 타입을 반환함. 따라서 TypeScript는 반환된 객체가 TableInfo 타입인지 알 수 없음
1. request.json()이 반환하는 데이터의 타입을 명시적으로 지정하여 TypeScript가 타입을 추론할 수 있도록 함
- 1-1
```ts
// POST /api/table/parliamentary?memberId={memberId}
http.post(ApiUrl.parliamentary, async ({ request }) => {
const url = new URL(request.url);
const memberId = url.searchParams.get('memberId');
const result = (await request.json()) as PostDebateTableResponseType;
// This console log calling shows error(ts(2339)) but will be executed with any problems.
console.log(
`# memberId = ${memberId}, tableAgenda = ${result?.info.agenda}, tableName = ${result?.info.name}`,
);
```
- 1-2
```ts
// PUT /api/table/parliamentary/{tableId}?memberId={memberId}
http.put(ApiUrl.parliamentary …
```
=> [FIX] Mock Handler 파일에서 타입 에러 해결 

src/apis/responseTypes.ts, src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx, src/components/ErrorBoundary/ErrorPage.tsx, src/index.css, src/main.tsx, src/page/TimerPage/TimerPage.tsx, src/route.tsx
closed #64 
- `ErrorBoundary` 도입
- BE와의 협의 사항에 따라 `ErrorResponseType` 수정
- /src/components/ErrorBoundary/ErrorPage.tsx
예외 발생 시 출력되는 UI
- /src/components/ErrorBoundary/ErrorBoundary.tsx
예외 발생을 탐지하고 이를 핸들링하는 클래스
1. 예외가 발생할 수 있는 컴포넌트의 ***가능한 바로 상단***에서 해당 컴포넌트를 아래와 같이 감싼다:
```tsx
export function PossibleErrorComponent() {
return (
<ErrorBoundary>
{/* 컴포넌트 코드 */}
</ErrorBoundary>
)
}
```
2. 의도하지 않은 동작이 발생하는 경우, 아래 코드와 같이 `throw`를 사용하여 예외를 던진다. 여기서 `Error`의 매개변수로 들어가는 `string` 매개변수는 ErrorBoundary에서 `error.message`로 접근할 수 있다.
```tsx
// TimerPage.tsx
if (isError || data === null) {
throw new Error('Failed to get data from server.');
}
// ErrorBoundary.tsx
class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
// 생략
static getDerivedStateFromError(error: Error): …
```
=> [FEAT] `ErrorBoundary` 도입

src/page/TableComposition/hook/useTableFrom.tsx, src/page/TableListPage/components/Table/Table.stories.tsx
closed #72 
현재 GitHub Actions의 [Deploy-Production](https://github.com/debate-timer/debate-timer-fe/actions/workflows/deploy-production.yml) 시나리오가 계속 실패하는 오류가 있어, 문제와 관련된 파일을 수정하였습니다. 제 개인 로컬 환경에서의 빌드 및 Deploy-Production 시나리오를 [수동으로 실행](https://github.com/debate-timer/debate-timer-fe/actions/runs/12879212393) - 단, AWS 배포 직전에 수동으로 취소하여 배포가 실제로 진행되진 않음 - 하여 빌드가 잘 되는 것을 확인하고 PR을 올립니다.
**\src\page\TableComposition\hook\useTableFrom.tsx**
\src\page\TableComposition\TableComposition.tsx에서 정의된 TableCompositionStep 상수 값이 한글(타임박스입력 등)에서 영어(TimeBox)로 바뀌면서 발생한 오류 해결
**\src\page\TableListPage\components\Table\Table.stories.tsx**
\src\type.ts에서 정의된 Type 상수 값이 한글(의회식 토론 등)에서 영어(PARLIAMENTARY)로 바뀌면서 발생한 오류 해결
- 치코(@jaeml06)님 작업과 관련된 사항으로 판단되어, 혹시 제가 잘못 수정한 부분이 있는지 확인해주시면 감사하겠습니다.
- 추가로 현재 GitHub Actions의 …
=> [HOTFIX] GitHub Actions 빌드 실패 문제 해결

.env.dev-mock, .env.development, .gitignore, src/apis/endpoints.ts, src/apis/primitives.ts, src/components/ErrorBoundary/ErrorBoundary.tsx, src/hooks/useModal.tsx, src/main.tsx, src/page/TableComposition/components/DeleteConfirmContent/DeleteConfirmContent.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableListPage/components/Modal/DeleteModalButton.tsx, src/page/TimerPage/TimerPage.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummary.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummaryItem.tsx, src/page/TimerPage/components/Timer/TimerComponent.tsx, src/page/TimerPage/components/Timer/TimerController.tsx, src/page/TimerPage/components/common/TimerDisplay.tsx, src/page/TimerPage/components/common/TimerTextButton.tsx, vite.config.ts
closed #74 
**추가 작전 시간 타이머 관련**
- 추가 작전 시간 타이머 구현
- `useModal` 훅에 기본 지정되어 있던 TailwindCSS 너비 제거 및 이에 영향을 받는 모든 모달 컴포넌트의 모양 수정
**API 관련**
- API 요청을 위한 기본 URL을 'https://api.dev.debate-timer.com' 으로 변경
- API 요청 시 CORS 오류가 발생하지 않도록 API 요청 관련 소스 코드 및 Vite 프로젝트 설정 수정
- 추가 작전 시간 타이머는 타이머 화면에서 '추가 작전 시간'이라고 적힌 버튼을 눌러 사용 가능
- 남은 시간에 따른 배경색 변경이 없음
- 30초에 1번, 0초에 2번 종이 울림
- 시작 버튼을 통해 타이머를 시작할 수 있고, 일시정지 버튼을 통해 타이머를 일시정지할 수 있음
- 30초 및 1분 단위로 사용자가 원하는 만큼 타이머 잔여 시간을 더하거나 뺄 수 있음 (단, 0 이하로 감소하지 않음)
- 타이머가 0초에 다다르면, 토론 타이머와는 다르게 음수로 내려가지 않으며 0에서 타이머가 정지함
- 추가 작전 시간 타이머를 호출한 순서를 기준으로, 이전 순서 / 현재 순서 / 다음 순서의 정보를 요약하여 화면 하단에 표시
- 추가 작전 시간 타이머를 열었을 때, 타이머 화면에서 사용 가능한 키보드 이벤트(스페이스, 화살표 등)는 비활성화되며, 오직 마우스로만 조작 가능
- @coli-geonwoo 의도하셨던 기능과 디자인이 잘 적용되어 있는지 의견 남겨주시면 감사하겠습니다!
=> [FEAT] 추가 작전 시간 타이머 구현 외

src/apis/primitives.ts
- #83
- 이슈 완전히 해결 시 수동으로 닫을 예정
- Vite의 `development` 모드에서 우리는 vite.config.ts에서 정의된 프록시 정책을 통해 '/api/endpoint' 형태의 URL을 'https://서버.주소.어쩌구/api/endpoint' 형태로 변환하여 사용했었음 (자세한 설명은 [링크](https://github.com/debate-timer/debate-timer-fe/pull/77#issuecomment-2607009303) 참고)
- 그러나 해당 프록시 정책은 Vite의 `production` 모드에서 제대로 동작하지 않는다는 사실을 확인
```ts
// Singleton Axios instance
const axiosInstance = axios.create({
baseURL:
import.meta.env.MODE !== 'production'
? undefined
: import.meta.env.VITE_API_BASE_URL,
timeout: 10000,
headers: {
'Content-Type': 'application/json',
},
});
```
- `production` 모드에서만 모든 통신의 기반이 되는 `AxiosInstance`에 `baseURL` 변수를 설정해주면 해결 가능
- 일단 `npm run preview` 명령어를 통해 CORS 오류를 보았고, 적절한 URL에 요청이 이루어지고 있는 것은 확인함
- 다만 요청이 'https://서버.주소.어쩌구/api/api/endpoint' 형태로 이루어지고 있음
- 이 부분은 아마 …
=> [HOTFIX] 배포된 앱이 서버와 통신하지 못하는 문제 수정

package-lock.json, src/layout/components/header/StickyTriSectionHeader.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx, src/page/TableListPage/TableListPage.test.tsx, src/page/TableListPage/TableListPage.tsx, src/page/TableOverviewPage/TableOverview.tsx, src/page/TimerPage/TimerPage.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx, src/page/TimerPage/components/common/TimerDisplay.tsx
closed #89
- TimerPage에서 기존 헤더 오른쪽에 표시되던 주제를 헤더 가운데로 이동
- TimerPage 헤더에 테이블 조회 화면으로 돌아가는 버튼 추가
- TimerPage에서 타이머가 동작하지 않을 때 의도하지 않은 벨이 울리는 버그 수정
- TimerPage의 작전 시간 타이머에서 동작 중인 경우 일시정지 버튼, 정지 중인 경우 시작 버튼만 표시되도록 하여, 동작 여부에 대한 사용자의 시인성 개선
- TimerPage에서 주제를 불러오지 못했을 경우의 예외 처리 코드 보강
- 헤더의 각 하위 요소(`Right`, `Center`, `Left`)에 `flex-1` 태그를 추가하여 각자 동일한 너비를 분배받을 수 있도록 개선
- TableOverviewPage에서 헤더 왼쪽에 표시되는 페이지 이름의 시인성 개선
별도 없음
=> [FIX] QA에서 식별한 버그 해결 - 숀

src/hooks/mutations/useDeleteParliamentaryDebateTable.ts, src/page/LoginPage/LoginPage.test.tsx, src/page/LoginPage/LoginPage.tsx, src/page/TableListPage/components/Table/Table.tsx
closed #90
- TableList 화면에서 토론 유형이 영어(PARLIAMENTARY)로 표시되는 문제
- TableList 화면에서 토론 시간이 초가 아니라 분으로 표시되는 문제
- TableList 화면에서 테이블을 삭제한 후 화면이 다시 렌더링되지 않는 문제
- Login 화면에서 상단 바에 "헤더", "의회식", "제목"이라고 적힌 불필요한 텍스트가 표시되는 문제
- TableList 화면에서 테이블을 삭제한 후 화면이 다시 렌더링되지 않는 문제 해결하기 위해
```ts
import { useMutation } from '@tanstack/react-query';
import { deleteParliamentaryDebateTable } from '../../apis/apis';
interface DeleteParliamentaryTableParams {
tableId: number;
memberId: number;
}
export function useDeleteParliamentaryDebateTable() {
return useMutation({
mutationFn: async ({ tableId, memberId }: DeleteParliamentaryTableParams) =>
await deleteParliamentaryDebateTable(tableId, memberId),
onSuccess: () => {
alert('테이블이 제거되었습니다.');
// 삭제 성공 후 페이지 강제 새로고침
window.location.reload();
},
onError: (error) => { …
```
=> [FIX] QA에서 식별한 버그 해결 - 엘

.github/workflows/deploy-storybook.yml, package.json, src/mocks/handlers.ts, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
closed #80
1. mock에서 드래그앤 드롭이 다음과 같이 UI가 깨지는 문제가 있어서 로직의 문제인줄 알았으나 mock에서 type이 CROSS여서 해당 UI가 비어서 발생한 문제였습니다.
https://github.com/user-attachments/assets/7abc394f-6c25-4eaa-aa7b-e0623c190d74
여기서 궁금증이 현재는 중립 상태는 Time_Out일 경우에만 존재하게 작성했습니다. CROSS도 중립인 것인지 궁금합니다.
2. 지금까지는 storybook을 배포하기 위해서는 명령어를 직접 입력해야했으나 PR이 닫히면 자동으로 배포되도록 변경하였습니다.
=> [FIX, CHORE] mock에서 드래그앤 드롭 UI가 깨지는 문제 수정, Storybook 자동 배포 yml 작성

src/hooks/mutations/useDeleteParliamentaryDebateTable.ts
closed #98 
```ts
export function useDeleteParliamentaryDebateTable() {
return useMutation({
mutationFn: async ({ tableId, memberId }: DeleteParliamentaryTableParams) =>
await deleteParliamentaryDebateTable(tableId, memberId),
onSuccess: () => {
alert('테이블이 제거되었습니다.');
// 삭제 성공 후 페이지 강제 새로고침
window.location.reload();
},
onError: (error) => {
console.error('Error deleting parliamentary table:', error);
alert('테이블 삭제에 실패했습니다.');
},
});
}
```
🚨 기존 코드 (window.location.reload())의 문제점
현재 코드에서는 테이블 삭제 후 전체 페이지를 강제로 새로고침 (window.location.reload()) 합니다.
이는 다음과 같은 문제점이 있습니다.
🔴 문제점
불필요한 전체 페이지 리로드
페이지 전체를 새로고침하면 불필요한 네트워크 요청이 발생하여 속도가 느려짐.
React Query의 캐싱 기능을 제대로 활용하지 못함.
기존 상태(state) 유지 불가
새로고침되면 **현재 보고 있던 상태(스크롤 위치, UI 상태 등)**가 모두 사라짐.
예를 들어 사용자가 특정 필터링을 하고 있었다면, 삭제 후 다시 처음 상태로 돌아감.
비효율적인 사용자 …
=> [FEAT] invalidateQueries 사용하여 Table 삭제 시 즉시 업데이트 반영

src/hooks/useDragAndDrop.tsx, src/layout/components/main/ContentContanier.tsx, src/page/TableComposition/TableComposition.test.tsx, src/page/TableComposition/TableComposition.tsx, src/page/TableComposition/components/DebatePanel/DebatePanel.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
closed #100
- 테이블 수정과 생성의 플로우가 같아 뷰 상으로 유저가 생성과 수정과정을 구분할 수 있도록 반영
- 타임박스가 헤더를 침범하는 문제를 수정
- 드래그&드롭 기능을 사용자가 인지할 수 있도록 시인성 개선
mode에 따라 TableComposition내의 버튼과 헤더 문구가 수정되도록 변경하였습니다.
기존 수정 시 화면
변경 후 수정 시, 화면 
헤더 문구를 -> 토론 정보를 수정해주세요 로 변경
버튼 문구를 -> 타임박스 수정하기, 테이블 수정하기 로 변경
useDragAndDrop의 getDraggingStyles에서  transform: 'translateY(0)', 때문에 css 스택이 헤더 위로 올라가는 문제가 발생.
해당 css를 이용하지 않고 DefaultLayout의 ContentContanier에 overflow-auto를 사용하여 헤더를 침범하지않게 수정
기존 디자인
수정후 디자인
=> [REFACTOR] 1차 UT에 있었던 1, 2순위 수정 사항 반영

src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
closed #108 
`useTimer` 훅 사용 시 불필요한 매개변수가 포함되어 빌드가 진행되지 않는 오류를 수정했습니다.
없음
없음
=> [FIX] `useTimer` 훅 매개변수 오류 수정

src/apis/axiosInstance.ts
closed #114
access token 만료 시, refresh 토큰으로 access toekn이 최신화 되지않는 오류 수정
=> [FIX] access token 만료 시, refresh 토큰으로 access toekn이 최신화 되지않는 오류 수정 

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml, package-lock.json, src/apis/primitives.ts, src/components/GoogleButton.tsx, src/page/LoginPage/LoginPage.test.tsx, src/page/TimerPage/TimerPage.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx, src/page/TimerPage/components/Timer/TimeTableItem.tsx, src/page/TimerPage/components/Timer/TimerComponent.tsx, src/page/TimerPage/components/Timer/TimerController.tsx, src/page/TimerPage/components/Timer/TimerTimeTable.tsx, src/page/TimerPage/components/common/FirstUseToolTip.tsx, src/page/TimerPage/components/common/HeaderButtons.tsx, src/page/TimerPage/components/common/TimerDisplay.tsx, src/page/TimerPage/components/common/TimerTextButton.tsx, src/util/validateUserAgent.ts, tailwind.config.js
closed #121 
- 불완전한 반응형 레이아웃 적용
- 임시 토론 시간표 추가 및 이에 따른 이전 차례 요약과 다음 차례 요약 제거
- 30s, 0s 효과음 켜고 끌 수 있는 체크박스 추가
- 사용자의 User Agent 확인하여 일부 웹 뷰 환경에서 로그인 버튼 비활성화
- Google 로그인 버튼 디자인 일부 개선
- PR이 병합되지 않은 채로 닫혀도 배포가 진행되는 문제 수정
말 그대로 불완전한 수준의 반응형 레이아웃을 적용했습니다. 이 말은, 여전히 모바일 환경에서는 사용하기 어려울 수 있으나, PC 웹 브라우저 환경에서는 가로 폭을 어느정도 줄여도 대응이 가능하다는 말입니다. 이를 위해 반영한 변경 사항은 간단하게는 아래과 같습니다:
- 모바일 환경에서 텍스트 크기 감소
- 모바일 환경에서 아이콘 크기 감소
- 모바일 환경에서 일부 컴포넌트의 가로 너비 감소
- 모바일 환경에서 타이머와 시간표가 세로로 정렬됨 (웹 환경에서는 가로로 정렬)
진지하게 논의가 진행되었던 토론 시간표를 화면 우측에 추가했습니다. 원래는 계획에 없었으나, 모킹 기능이 제대로 작동하지 않고 무한 렌더링에 걸려 이 문제를 해결하고자 TimerPage를 싹 갈아 엎다가 그냥 하는 김에 추가했어요. 일단은 간단하게 디자인하였으니, 본격적으로 목업이 나오면 그에 맞추어 다시 수정 진행할게요. 기능 세부 설명은 아래와 같습니다:
- 전체 토론 순서를 시간표에 위부터 순서대로 표시
- 현재 토론 순서는 빨간 색의 움직이는 테두리와 그라데이션 배경으로 강조됨
- 그 외 토론 순서는 회색으로 강조되지 않음
- 토론 시간표 아래의 이전 …
=> [FEAT] 타이머 개선 외

src/apis/apis.ts, src/apis/responseTypes.ts, src/constants/languageMapping.ts, src/hooks/mutations/useAddTable.ts, src/hooks/mutations/usePutParliamentaryDebateTable.ts, src/page/TableComposition/TableComposition.tsx, src/page/TableComposition/components/DebatePanel/DebatePanel.tsx, src/page/TableComposition/components/DropdownForDebateType/DropdownForDebateType.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.stories.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx, src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx, src/page/TableComposition/hook/useTableFrom.tsx, src/page/TableOverviewPage/TableOverview.stories.tsx, src/page/TableOverviewPage/TableOverview.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummary.tsx, src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummaryItem.tsx, src/page/TimerPage/components/DebateInfoSummary.tsx, src/page/TimerPage/components/Timer/TimeTableItem.tsx, src/page/TimerPage/components/Timer/TimerComponent.tsx, src/page/TimerPage/components/Timer/TimerTimeTable.tsx, src/type/type.ts
closed #122 
- 지원되지 않는 토론 유형(시간 총량제) 제거
- 30초, 발언종료 종소리 on & off 기능 추가
- 헤더 UI를 overview페이지와 타이머 페이지와 동일하게 변경.
- 타임 박스 수정에 작전시간에서 다른 유형으로 변경시 오류가 발생.
- DebateInfo 인터페이스 명을 TimeBoxInfo로 변경
- 하드코딩된 타입을 DetailDebateInfo 타입으로 공통화
---
아직 지원하지 않은 시간총량제 토론을 제거함으로써 사용자에게 혼란을 주는 일을 없앴습니다.
다음과 같이 알림을 선택할 수 있는 체크박스를 추가했습니다.
테이블 생성 페이지에서의 헤더 UI를 공통화했습니다.
기존의 수정흐름에서 타임박스가 작전시간인 상태에서 다른 유형으로 변경 후 수정하기 버튼 클릭 시 에러가 발생하는 문제를 수정.
DebateInfo 인터페이스명을 실제 TimeBox에서 사용되기 때문에 더 정확한 네이밍으로 변경하였습니다.
```ts
name: string;
agenda: string;
warningBell: boolean;
finishBell: boolean;
```
하드 코딩된 타입을 DetailDebateInfo으로 공통화했습니다.
=> [FEAT] 토론 테이블 생성, 수정 개선

src/components/HeaderTableInfo/HeaderTableInfo.tsx, src/components/HeaderTitle/HeaderTitle.tsx, src/components/IconButton/IconButton.tsx, src/layout/components/header/StickyTriSectionHeader.tsx, src/page/TableComposition/TableComposition.test.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx, src/page/TableListPage/TableListPage.tsx, src/page/TableOverviewPage/TableOverview.tsx
closed #130
- StickyTriSectionHeader의 로직을 UI와 다양한 헤더에 대응될 수 있게 개선
- 헤더에 표시되는 정보를 공통 컴포넌트로 분리
StickyTriSectionHeader를 더 다양한 헤더 스타일을 대응할 수 있게 개선했습니다.
```tsx
<DefaultLayout.Header.Right defaultIcons={['home', 'logout']}/>
```
오른쪽 헤더영역에서 home과 logout을 선택해서 렌더링할 수 있습니다. 헤더에 표시되는 버튼의 순서도 배열의 순서로 변경 가능합니다. 
후에 자주 재사용되는 헤더가 추가되는 경우, StickyTriSectionHeader.Right의 switch문에 추가하면됩니다.
```tsx
switch (iconName) {
case 'home':
return (
<div key={`${iconName}-${index}`}>
<IconButton
icon={<IoMdHome size={24} />}
onClick={() => navigate('/')}
/>
</div>
);
case 'logout':
return (
<div key={`${iconName}-${index}`}>
<IconButton
icon={<IoLogOut size={24} />}
onClick={() => logoutMutate()}
/>
</div>
);
default:
return null;
}
})}
```
추가로 단기성 아이콘 버튼을 표시할 필요가 있는 경우,
```tsx
<DefaultLayout.Header.Right …
```
=> [REFACTOR] 헤더 UI를 공통화 

src/layout/components/main/ContentContanier.tsx
closed #138
- padding유무를 props로 전달
```tsx
import { PropsWithChildren } from 'react';
interface ContentContainerProps extends PropsWithChildren {
noPadding?: boolean;
}
export default function ContentContanier({
children,
noPadding = false,
}: ContentContainerProps) {
return (
<main
className={`relative flex flex-grow flex-col items-center gap-2 overflow-auto ${
noPadding ? '' : 'px-8 py-4'
}`}
>
{children}
</main>
);
}
```
props로 패딩 유무를 전달 받는다. 
default로 패딩이 존재하고
```tsx
<DefaultLayout.ContentContanier noPadding={true}>
```
일 경우 패딩을 제거할 수 있다.
=> [FEAT] ContentContanier의 padding유무를 props로 전달

src/page/TimerPage/components/TimeTable.tsx, src/page/TimerPage/components/TimeTableItem.tsx
closed #154 
- 이전/다음 차례 아이콘 좌우로 수정
- 찬성 및 반대 시간표의 중심이 맞지 않는 현상 수정
=> [DESIGN] 타이머 페이지 수정 

src/components/ErrorBoundary/ErrorPage.tsx, src/components/ErrorBoundary/NotFoundPage.tsx, src/components/ProsAndConsTitle/PropsAndConsTitle.tsx, src/layout/components/footer/StickyFooterWrapper.tsx, src/page/LoginPage/components/LinkButton/LinkButton.tsx, src/page/TableComposition/TableComposition.test.tsx, src/page/TableComposition/components/DebatePanel/DebatePanel.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx, src/page/TableComposition/components/TimerCreationButton/TimerCreationButton.tsx, src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx, src/page/TableListPage/components/Modal/DeleteModalButton.tsx, src/page/TableListPage/components/Table/AddTable.tsx, src/page/TableOverviewPage/TableOverview.tsx
closed #151
- 시간표 조회 화면에 찬성, 반대 박스 간 margin 설정 ✅
- 타임박스 삭제/수정 아이콘 padding 추가 ✅
- 찬/반 타임박스 높이 맞추기 (중립 타임박스가 더 낮음) ✅
- 시간표 수정 화면에서 상단의 찬/반 사이 너비와 아래의 수정하기/토론하기 버튼 사이 너비를 일치 ✅
(수정하기/토론하기 버튼 사이 너비를 상단에 맞추기)
- 시간표 수정/조회 화면에서 하단 버튼 텍스트 굵게 ✅
- 시간표 수정/조회 화면에서 모든 요소 완전히 중앙 정렬 ✅
- 타임박스 모달 관련
- 유형, 입장, 시간, 발언자 세미볼드 ✅
- 시간표 설정 버튼 세미볼드 ✅
- 전반적으로 너비를 줄이자 ✅
- 수평 패딩 추가 ✅
- 텍스트 필드 정렬은 왼쪽으로 ✅
- ‘타임박스’ → ‘시간표’ 문자열 수정 ✅
시간표 상세페이지
- before
- after
시간표 수정 생성 페이지
- before
-after
시간표 수정 삭제 모달
- before
- after
=> [DESIGN] 시간표 설정 화면, 타임 박스 모달 피드백 사항 반영

src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx, src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #153
- 시간표 설정시, 작전시간 이후 다음 시간표 박스에도 작전시간이 들어가는 문제 수정
이전에는 타임 박스를 새로 생성할 때, 이전 타임 박스 설정 정보를 바탕으로 상태를 초기화하기 위해 indata를 props로 넘겼고 타임 박스를 수정할해당 타임박스 정보를 initdata로 같은 props로 넘김으로써 충돌이 발생했습니다. 이를 beforeData, initData로 분리하였습니다.
- before
https://github.com/user-attachments/assets/610b394d-b9aa-47cf-843a-78e5218d055c
- after
https://github.com/user-attachments/assets/e862c150-4ce4-41fa-b803-4d5930d71407
=> [FIX] 작전시간 이후 다음 시간표 박스에도 작전시간이 들어가는 문제 수정

src/index.css, src/layout/components/header/StickyTriSectionHeader.tsx, tailwind.config.js
closed #156 
- 주 색상을 `#FECD4C`으로 변경
- 배경 색상(헤더 + 컨테이너)을 `#F6F5F4`로 변경
- neutral 색상 테이블에 300~900 삭제 (기본값 쓰기로 함)
뭔가 배경이 둘 다 새하얀 편이라 구분이 어렵지만... 옆에 바로 두고 비교하면 다르게 보이기는 합니다.
없음
=> [DESIGN] 테마 색상 변경

src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #166
이전 시간표에 따라 시간표 생성 모달 기본 입장이 변경되지 않는 문제 수정
- before
https://github.com/user-attachments/assets/aa2a4d06-499f-492f-9048-1d8959d7d16d
- after
https://github.com/user-attachments/assets/1ada211b-59ea-4088-9521-864a04ff2e21
=> [FIX] 이전 시간표에 따라 시간표 생성 모달 기본 입장이 변경되지 않는 문제 수정

src/hooks/useModal.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableListPage/components/Modal/DeleteModalButton.tsx
closed #155 
다른 거 끝나고 한다는 게 까맣게 잊어버렸군요... 늦어서 죄송합니다 ㅜㅜ
- 모달에 닫는 버튼(X)의 출력 여부를 선택할 수 있는 boolean 변수 추가
- 타임박스 삭제 모달에 닫기 버튼 지우고 취소 버튼 추가
- 테이블 삭제 모달에 닫기 버튼 지우고 취소 버튼 추가
```tsx
const { ... } = useModal({isCloseButtonExist: false})
```
위처럼 사용하시면, 모달에 닫기 버튼(X 버튼)이 나타나지 않습니다.
없음
=> [DESIGN] `useModal` 일부 변경

src/page/TableListPage/TableListPage.tsx, src/page/TableListPage/components/Table/Table.stories.tsx, src/page/TableListPage/components/Table/Table.tsx, src/type/type.ts
closed #170 
- 토론 테이블에 시간 대신 주제 표시함
- 주제가 없는 경우 '주제 없음'으로 표시
- 주제가 긴 경우 말줄임표 사용, 호버 시 툴팁으로 전체 텍스트 확인 가능
합류 후 첫 코드 수정이라 놓친 부분이 있을까 걱정되네요. 코드 리뷰 부탁드립니다-!
=> [DESIGN] 토론 테이블에 주제 표시, 주제 긴 경우 툴팁 추가

src/mocks/handlers.ts, src/page/TimerPage/components/TimeTable.tsx, src/page/TimerPage/components/TimeTableItem.tsx, src/page/TimerPage/stories/TimeTable.stories.tsx
closed #169 
- 시간표 아이템 개수 5개로 고정되도록 변경
- 현재 순서가 무조건 중앙(3번째)에 고정되도록 변경
없음
=> [DESIGN] 시간표 아이템 개수 5개로 고정되도록 변경

src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #179
죄송합니다. 계속 같은 문제로 PR을 작성하게 되네요. 수정부분 PR올립니다.
작전시간 선택 후, 다임 시간표생성에서 작전시간이 유지되는 문제 수정.
- before
https://github.com/user-attachments/assets/442d7843-ad8a-4b06-8b6b-0d5eeda406e5
- after
https://github.com/user-attachments/assets/e4742404-8839-4f3e-97c0-7978af8ec99b
없음
없음
=> [FIX] 작전시간 선택 후, 다임 시간표생성에서 작전시간이 유지되는 문제 수정

src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/ErrorBoundary/ErrorPage.tsx
closed #181
- 에러페이지에서 홈으로 가기 버튼이 동작하지 않는 문제 수정 
ErrorBoundary.tsx 페이지에서 에러가 발생하면 hasError의 상태를 true 변경합니다. 하지만 기존에 홈으로 가기 버튼을 클릭해서 hasError의 상태가 여전히 true이기 때문에 에러페이지가 계속 보이게 됩니다. 
그래서 다음과 같은 함수를 만들어 이 에러 상태를 초기화 가능하게 추가했습니다.
```
resetError = () => {
this.setState({ hasError: false, message: defaultMessage, stack: defaultStack });
};
```
없음
없음
=> [FIX] 에러페이지에서 홈으로 가기 버튼이 동작하지 않는 문제 수정 

.github/workflows/Issue_Noti.yml, .github/workflows/PR_Comment_Noti.yml
closed #172 
- PR 댓글 알림 스크립트의 제어 문자(`\n` 등)가 제대로 동작하지 않는 오류 해결
- 이슈 생성 알림 스크립트의 제어 문자가 제대로 동작하지 않는 오류 해결
- 이슈 생성 알림 스크립트가 실행되지 않는 오류 해결
GitHub Copilot의 답변을 첨부합니다:
> 이 오류는 COMMENT_BODY 변수에 포함된 내용이 환경 변수로 설정될 때 문제가 발생하는 것입니다. 특히, COMMENT_BODY에 포함된 줄바꿈이나 특수 문자가 문제를 일으킬 수 있습니다. 이를 해결하기 위해 COMMENT_BODY를 환경 변수로 설정하기 전에 인코딩할 수 있습니다.
조언에 따라, base64로 인코딩하여 환경 변수로 설정 후, jq로 전송하기 직전 디코딩하여 복구하는 식으로 수정했습니다.
jq에 페이로드를 싣을 때, `jq -R @json` 명령어를 사용하여 제어 문자가 잘 이스케이프되도록 수정했습니다.
> -R (--raw-input): Reads input as a raw string instead of treating it as JSON.
@json: Converts the raw string into a valid JSON string by escaping special characters.
없음
없음
=> [FIX] Discord 스크립트 오류 수정

src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #185
- 기존에 시간표 생성에 이전 설정 시간표에 따라 초기에 선택된 발언자가 달라지는데 이전이 작전시간이었다면, 발언자가 없음으로 나타나는 문제를 수정합니다.
- before
https://github.com/user-attachments/assets/dc8bffc6-0710-48b4-9c21-751b61707206
-after
https://github.com/user-attachments/assets/8dcc3029-8718-43c0-b3bd-dbb27a50643f
=> [FIX] 초기 speakerNumber를 상황에 맞게 초기화

.github/workflows/Issue_Noti.yml, .github/workflows/PR_Comment_Noti.yml, src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #188
main 병합을 통한 prod 배포
=> [DEPLOY] prod 배포

src/page/TimerPage/components/TimeTable.tsx, src/page/TimerPage/components/TimeTableItem.tsx, src/page/TimerPage/components/Timer.tsx, src/page/TimerPage/stories/TimeTableItem.stories.tsx
closed #192 
- `TimeTableItem`의 너비를 `min-w-[360px]`로 설정, 너비를 고정하되 오버플로우 발생 시에만 늘어나도록 수정
- 시간표 자체의 너비를 20px 늘림
- 발언자 번호가 1번으로 하드코딩되어 있던 부분을, 실제 발언자 번호를 표시하도록 수정함
- 발언자 번호가 `undefined`일 경우에는, 발언자 번호를 출력하지 않도록 구현
교차 질의 관련 시간표 아이템 예시
없음
=> [FIX] 타이머 버그 해결

src/components/DialogModal/DialogModal.stories.tsx, src/components/DialogModal/DialogModal.test.tsx, src/components/DialogModal/DialogModal.tsx, src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx, src/page/TableListPage/components/Modal/DeleteModalButton.tsx
closed #173
- 대화 상자형 모달 별도 컴포넌트인 `DialogModal`로 분리
- 해당 모달을 사용하는 페이지에 위 변경사항 적용
- `DialogModal` 관련 Storybook 및 테스트 코드 추가
```tsx
<DialogModal
leftText="왼쪽"
rightText="오른쪽"
onLeftClick={() => {}}
onRightClick={() => {}}
isRightBold={true}
>
{/** 여기에 모달 안에 들어갈 텍스트 메시지 등 구현 */}
</DialogModal>
```
- `leftText` 왼쪽 버튼에 들어갈 텍스트
- `rightText` 오른쪽 버튼에 들어갈 텍스트
- `onLeftClick` 왼쪽 버튼 클릭 시 동작
- `onRightClick` 오른쪽 버튼 클릭 시 동작
- `isLeftBold` 왼쪽 버튼의 텍스트 볼드 표시 (기본값 `false`)
- `isRightBold` 오른쪽 버튼의 텍스트 볼드 표시 (기본값 `false`)
해당 모달의 컨텐츠 영역에는 기본적으로 어떤 padding도 적용되어 있지 않으니, 모달 사용 시 padding을 직접 넣어주어야 함
없음
없음
=> [REFACTOR] 대화 상자형 모달 별도 컴포넌트로 분리

.github/workflows/Issue_Noti.yml, .github/workflows/PR_Comment_Noti.yml
closed #204 
- 새 이슈 발행 시 Discord 알림 스크립트 수정
- 새 PR 댓글이 달렸을 때 Discord 알림 스크립트 수정
전부터 `COMMENT_BODY` 관련한 내용이 계속 문제를 일으켜 그냥 삭제했습니다. 현재 상황에서 중요한 이슈도 아니고, 게시글 본문은 Discord 알림에 있는 링크 타고 GitHub에서 직접 확인할 수 있으니까요. 같은 문제로 더 이상의 PR 올릴 일 없게 그냥 싹을 잘라버립시다.
없음
없음
=> [FIX] Discord 알림 스크립트 오류 수정

src/components/DialogModal/DialogModal.tsx, tailwind.config.js
closed #198
- 이용하지 않는 sub 색상 제거
- 주 색상에서 채도를 변경한 색상 추가 ex) main501
- 진영(camp) 색상 변경
1. 요구사항인 모달 버튼을 neutral-1000으로 변경하는 곳이 어느곳을 말하는 것인지 확인이 어렵습니다. 어느 부분을 말하는 것일까요?
2. neutral-900으로 사용한 부분을 local에서는 neutral-1000으로 변경하는 작업을 하긴 했는데 이를 PR에 반영하는 것이 맞을지 궁금하네요. 개인적으로는 이 작업과 별도로 나중에 한번에 개선하는 것이 좋을 것 같기도 합니다. 건드리는 파일이 많아서...
=> [CHORE] 스타일 가이드 변경

src/apis/apis/parliamentary.ts, src/apis/responses/parliamentary.ts, src/hooks/mutations/usePatchParliamentaryDebateTable.ts, src/page/TableOverviewPage/TableOverview.tsx
closed #193 
- PR #208 이후 변경 사항 머지 후 PATCH 로직 적용
- /api/table/parliamentary/{tableId}/debate 호출 로직 추가
- '토론하기' 버튼 클릭 시 PATCH API 호출
- 성공 시 테이블 페이지로 이동, 실패시 에러 로깅
없음
없음
=> [FEAT] parliamentary/debate api 토론하기 버튼 재연결

src/components/DialogModal/DialogModal.tsx
closed #212
`DialogModal` 버튼에 다음 호버 색상을 추가하였습니다:
- 왼쪽 `neutral-300`
- 오른쪽 `brand-main`
없음
=> [DESIGN] `DialogModal` 버튼 호버 색상 추가

.github/workflows/deploy-storybook.yml
closed #222 
- 현재 이 저장소는 Squash-merging 후 기존 브랜치를 삭제하는 전략 사용 중
- 그러나 병합 후 브랜치가 삭제되어, Storybook 배포 스크립트가 삭제된 Feature 브랜치의 헤드를 찾지 못해 배포가 진행되지 않았음
배포 명령어를 다음과 같이 개선:
```yaml
run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --sha=${{ github.sha }} --exit-zero-on-changes
```
세부 옵션에 대한 설명:
- `--project-token` Chromatic 배포에 사용되는 고유 토큰
- `--sha` 배포할 기준 커밋의 해시 번호 (SHA)
- `--exit-zero-on-changes` React 컴포넌트에 직접적 디자인적 변경 사항이 있어도 오류를 뱉지 않고 계속 진행할 것을 명령
이상의 명령어는 GitHub Actions 러너에게 develop 브랜치에서 헤드를 찾아 배포하도록 함
없음
원래는 PR이 단순히 닫히는 게 아니라 병합까지 되어야만 스크립트가 동작하도록 수정했었는데, 이러면 너무 융통성이 없어져서 이 조건문을 지웠습니다. 이 조건문이 들어가면 생기는 또 하나의 단점은, 지금 `workflow_dispatch` 옵션으로 인해 수동 실행이 가능하도록 설정되어 있는데, 조건문으로 인해 사실상 수동 실행이 막힌다는 점입니다.
이 부분에 대한 여러분 의견이 궁금합니다.
=> [FIX] Storybook 배포 진행되지 않는 문제 수정

src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
closed #230
- speechType이 string으로 변경됨에 따른 조건문 수정
(케이티 브랜치에서 촬영한 것이어서 발언 아이콘은 무시해도됩니다.)
없음
=> [FIX] 사전에 작전시간을 설정한 경우, 타이머 페이지에서 작전 시간 선택 버튼이 보이지 않도록 수정

src/hooks/useModal.tsx, src/page/CustomizeTimerPage/CustomizeTimerPage.tsx, src/page/CustomizeTimerPage/components/FirstUseToolTip.tsx, src/page/CustomizeTimerPage/components/NormalTimer.tsx, src/page/CustomizeTimerPage/hooks/useNormalTimer.ts, src/page/CustomizeTimerPage/stories/NormalTimer.stories.tsx, src/page/CustomizeTimerPage/stories/TimeBasedTimer.stories.tsx
closed #228
- 자유토론 타이머 중 `NormalTimer` 사용 시 키보드 일시정지(Space) 및 초기화(R) 동작하지 않는 문제 수정
- 자유토론 타이머의 특정 스타일 태그(`absolute 등`)로 인해, `FirstUseToolTip`이 깨져서 출력되는 문제 수정
- 자유토론 타이머의 툴팁에서 작전 시간 타이머 관련 내용 제거
`useModal`의 `z-20` 태그는 `TimeBasedTimer`의 가운데 진영 변경 버튼(Enter)이 `z-10`을 먹고 있어, 인덱스가 10보다 크지 않으면 모달 위로 버튼이 튀어나와 추가하였습니다.
없음
=> [FIX] 자유토론 타이머 오류 해결

src/page/CustomizeTimerPage/CustomizeTimerPage.tsx, src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
closed #232
기존  resetTimer의 호출되는 경우는
- R과 reset버튼을 눌렀을 때,
- 팀 전환간에 타이머 정보를 초기화할때,
2가지 경우다.
다음과 같이 진행할 경우, 
https://www.notion.so/2-QA-1cc1550c60cf8095af16ea3d5671f3b1
해당 QA에서 같이 가장 최신의 타이머 정보로 reset하기 어려운 문제가 있다.
이를 해결하기 위해 R과 reset버튼을 눌렀을 때와 팀 전환간에 타이머 정보를 초기화할때, 로직을 분리하였다.
수정 반영 화면
https://github.com/user-attachments/assets/cf999fd2-917e-4e60-854e-c7cc0e33d5f7
https://github.com/user-attachments/assets/1597c904-2f76-475b-ae86-35980f9d5763
증복없이 통합할 수 있는 방법이 있을까요?
=> [FIX] 커스텀 토론 페이지 자유토론 타이머 2차 QA 수정

src/page/CustomizeTimerPage/components/NormalTimer.tsx
closed #237
- NomalTimer의 헤더 문구가 설정된 문자열에 출력되지 않는 문제 수정
- 일반 타이머에서 중립에서는 팀 이름, 토론자 정보 제거
=> [FIX] NomalTimer의 헤더 문구가 설정된 문자열에 출력되지 않는 문제 수정

src/page/CustomizeTimerPage/components/NormalTimer.tsx
closed #239 
- 사용자 지정 토론 NormalTimer의 추가 작전 시간 발언자 정보 삭제
=> [FIX] 사용자 지정 토론 NormalTimer의 추가 작전 시간 발언자 정보 삭제

src/mocks/handlers/customize.ts, src/page/TableComposition/TableComposition.test.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/hook/useTableFrom.tsx
closed #243 
- **토론 유형 설정 드롭다운 박스 삭제**
`PARLIAMENTARY`/`CUSTOMIZED` 중 하나를 고를 수 있었던 드롭다운 박스를 아예 삭제했어요.
- **토론 생성 시 데이터 기본값을 `CUSTOMIZED`로 변경**
원래 토론 생성 시 기본값은 `PARLIAMENTARY`었는데, 이를 `CUSTOMIZED`으로 변경했어요.
위 2가지 변경 사항이 합쳐져서, 이제부터 새 토론 생성 시 `CUSTOMIZED`가 기본값이고, 이를 `PARLIAMENTARY`로 바꿀 수 있는 드롭다운 메뉴가 삭제됐기 때문에, 사용자는 토론 유형을 변경할 수가 없어요.
- 바뀌는 점은, 이제 사용자 지정 토론만 생성이 가능합니다
- 바뀌지 않은 점은, 이미 생성된 의회식 토론은 수정 및 사용이 가능합니다
기존에 존재하던 의회식 토론, 사용자 지정 토론을 고를 수 있었던 드롭다운 박스가 존재하지 않습니다.
없음
=> [CHORE] 의회식 토론 생성 차단

src/mocks/handlers/customize.ts, src/page/TableComposition/TableComposition.test.tsx, src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx, src/page/TableComposition/hook/useTableFrom.tsx
없음
사용자의 토론 유형 선택을 차단하고 기본값을 사용자 지정 토론으로 바꾸는 변경 사항 적용
없음
없음
=> [DEPLOY] 배포 진행

src/mocks/handlers/customize.ts, src/page/CustomizeTimerPage/CustomizeTimerPage.tsx, src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
closed #254
이전 타종 버그 수정에서는 처음부터 30초로 설정된 타이머는 타종하지 않았지만 30초에서 타이머를 멈추고 다시 재생 시, 타종을 하던 문제가 발생했어요.
해당 문제를 수정하기 위해 정확히 31초에서 30초로 가는 상황에서만 타종을 하는 로직이 필요하다고 판단하였습니다. 이전 초의 상태를 기억하는 useRef를 추가했어요
```ts
// 타이머의 이전상태를 저장(타종 31->30초인 상황에서만 타종하기위한 로직)
const prevTimer1Ref = useRef<{
speakingTimer: number | null;
totalTimer: number | null;
}>({
speakingTimer: null,
totalTimer: null,
});
const prevTimer2Ref = useRef<{
speakingTimer: number | null;
totalTimer: number | null;
}>({
speakingTimer: null,
totalTimer: null,
});
const prevNormalTimerRef = useRef<number | null>(null);
```
해당 상태를 타종을 담당하는 useEffect하단에 다음과 같이 변경하여 매번 이전 상태를 기억하도록 합니다.
```ts
useEffect(() => {
// 위의 벨 소리 로직...
// 이전 타이머 값 저장 (맨 아래에 추가)
prevTimer1Ref.current = {
speakingTimer: timer1.speakingTimer,
totalTimer: timer1.totalTimer, …
```
=> [FIX] 31초 -> 30초가 되는 순간에만 타종하도록 로직을 변경

.storybook/preview.tsx, src/components/RoundControlButton/RoundControlButton.tsx, src/page/CustomizeTimerPage/CustomizeTimerPage.tsx, src/page/CustomizeTimerPage/NormalTimerTestPage.stories.tsx, src/page/CustomizeTimerPage/NormalTimerTestPage.tsx, src/page/CustomizeTimerPage/components/AdditionalTimerControlButton.tsx, src/page/CustomizeTimerPage/components/AdditionalTimerController.tsx, src/page/CustomizeTimerPage/components/NormalTimer.tsx, src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx, src/page/CustomizeTimerPage/components/TimerController.tsx, tailwind.config.js
closed #250 
- 기존 storybook 에서는 자유토론타이머 페이지만 전체화면으로 확인 가능
- 따라서 별도의 일반타이머용 전체화면 테스트 페이지 추가
- 작은화면: 1280px 미만
- 중간화면: 1280px ~ 1450px
- 큰화면: 1450px 이상
- 각 breakpoint에 맞춰 고정된 크기 적용
- 차례 버튼(이전, 다음)도 함께 변화
storybook 또는 preview 로 테스트 부탁드립니다
=> [DESIGN] 타이머 반응형 구현

.github/workflows/deploy-development.yml, .github/workflows/deploy-production.yml
closed #288 
이 문제는 GitHub Actions 스크립트에서 환경 변수를 `vars.ENV`가 아니라 `secrets.ENV`로 참고하고 있었기 때문에 발생했습니다. dev 배포 스크립트와 prod 배포 스크립트 모두 `vars.ENV`로 수정하였습니다.
기존 배포 워크플로는 오직 PR이 병합될 때에만 실행 가능했습니다. 원래 GitHub Actions는 스크립트를 기본(default) 브랜치가 아닌 하위 브랜치에서도 실행 가능하지만, 이 조건에 의해 하위 브랜치에서 스크립트를 개선한 후 테스트할 수 없었습니다. 이 제한을 풀어 워크플로 개선 시 하위 브랜치에서도 테스트를 해 보고 문제를 조기에 식별할 수 있게 개선합니다.
없음
없음
=> [HOTFIX] 배포 워크플로가 환경 변수를 읽지 못하는 오류 수정
