- .github/ISSUE_TEMPLATE/-refactor-template.md
- .github/ISSUE_TEMPLATE/chore-template.md
- .github/ISSUE_TEMPLATE/docs-template.md
- .github/ISSUE_TEMPLATE/feat-template.md
- .github/ISSUE_TEMPLATE/fix-template.md
- .github/ISSUE_TEMPLATE/hotfix-template.md
- .github/ISSUE_TEMPLATE/refactor-template.md
- .github/ISSUE_TEMPLATE/ui-template.md
- .github/workflows/Auto_Issue_Setting.yml
closed #3
회의에서 정해진 대로 issue 템플릿과 자동 할당 yml을 작성하여 PR 요청합니다.
> [DOCS] ISSUE 템플릿과 자동 할당 구현

- .github/workflows/Auto_PR_Setting.yml
closed #5
PR 자동할당 yml 작성했습니다. 각각 yml스크립트가 무슨 일을 하는지 주석처리했으니 확인해보세요
> [DOCS] PR 자동할당 yml 작성

- .github/workflows/PR_Comment_Noti.yml
closed #7
백엔드의 yml파일을 참고하여 Discord comment를 yml을 만들었습니다.
dicord 알림으로 전파해야할 comment가 있다면 /noti 를 포함해서 comment를 작성해주세요
코드 리뷰의 경우 summint review를 이용해주세요
> [DOCS] Discord comment 알림 yml 작성

- .prettierrc
closed #12
기존 기본설정 환경에서 prettier 스크립트를 추가했습니다.
> [CHORE] prettier 설정 추가

- .github/workflows/CI.yml
closed #23
지속적 통합(CI)를 위한 yml파일을 작성했습니다
> lint와 test를 넣은 CI yml 파일 작성

- src/hooks/useDragAndDrop.tsx
- src/hooks/useThrottle.ts
- src/page/TableSetupPage/TableSetup.tsx
- src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
- src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.stories.tsx
- src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.tsx
closed #46
타임박스의 순서를 드래그 앤 드롭을 이용해서 수정할 수 있게 구현. 
이를 위해 리스트 항목을 재정렬할 수 있는 재사용 가능한 드래그앤드롭 기능을 제공하는 useDragAndDrop 커스텀 훅을 구현.
onMouseMove 핸들러에 스로틀링을 적용하여 빠른 마우스 이동 시에도 성능을 최적화.
**내부 상태**
```tsx
const dragIndexRef = useRef<number | null>(null); // 드래그 중인 항목의 인덱스
const itemHeightRef = useRef<number>(0); // 아이템의 평균 높이
const [hoverIndex, setHoverIndex] = useState<number | null>(null); // 호버 중인 인덱스
```
- dragIndex: 드래그가 시작된 아이템의 인덱스 (마우스를 누른 시점에 기록).
- hoverIndex: 마우스가 현재 어떤 위치(또는 어떤 아이템 인덱스)에 hover해 있는지.
- itemHeight: 아이템 하나의 평균 높이(또는 계산된 높이).
**handleMouseDown**
```tsx
const handleMouseDown = useCallback((index: number) => {
dragIndexRef.current = index;
}, []);
```
마우스를 누르는 순간, 이 아이템(index)을 드래그할 것이라고 저장.
**handleMouseMove**
```tsx
const handleMouseMove = useCallback(
(
e: …
```
> [FEAT] 타임박스의 수정을 드래그앤드롭으로 변경하는 기능 구현

- .vscode/settings.json
closed #61 
- VS Code 작업 영역에 대한 설정 파일 추가
- 별도 없음
- 설정 파일 확인하시고, 빼먹은 게 없는지 한 번 의견 남겨주시면 감사하겠습니다.
> [CHORE] VS Code 작업 영역에 대한 설정 파일 추가

- src/apis/responseTypes.ts
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx
- src/components/ErrorBoundary/ErrorPage.tsx
- src/index.css
- src/main.tsx
- src/page/TimerPage/TimerPage.tsx
closed #68
병합과정에서 에러바운더리 코드가 삭제된 문제가 발생했습니다. 이를 수정하기위해 PR을 올립니다.
> [HOTFIX] 에러바운더리 코드가 삭제된 것에 대한 반영

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- index.html
- package-lock.json
- package.json
- public/mockServiceWorker.js
- vite.config.ts
closed #78 
- vite-bundle-visualizer 사용하여 번들 크기 확인, 빌드 시 msw 등 API 모킹 관련 패키지 포함되지 않는 것 확인함
- vite-plugin-compression2 사용하여 번들을 gzip 형태로 압축하도록 설정함
**Git 저장소의 Environment 구분**
- 배포 환경을 `DEPLOY_DEV`와 `DEPLOY_PROD`로 구분
- [링크](https://github.com/debate-timer/debate-timer-fe/settings/environments)를 통해 확인할 수 있음
**GitHub Actions 워크플로에서 배포 환경 설정**
```yaml
name: Deploy-Development
jobs:
deploy:
runs-on: ubuntu-latest
environment: DEPLOY_DEV
```
- 워크플로의 `environment`에 각각 위에서 설정한 `DEPLOY_DEV`와 `DEPLOY_PROD`를 구분
- 이 구분을 통해 `ENV`라는 같은 이름으로 지정된 환경 변수를 각각 다른 환경에서 불러올 수 있음
```yaml
jobs:
deploy:
runs-on: ubuntu-latest
environment: DEPLOY_DEV
steps:
- name: Setup .env
run: echo "${{vars.ENV}}" > .env
```
- 환경 변수 파일을 생성하는 과정에서, [GitHub 저장소에서 지정된 각 환경에 따른 환경 변수 …
> [CHORE] 배포 최적화 및 배포 환경 구분

- src/apis/responseTypes.ts
- src/page/TableComposition/TableComposition.tsx
- src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
- src/page/TableOverviewPage/TableOverview.tsx
closed #85
- PostUserResponseType타입 수정
id가 1 타입에서 number타입으로 변경
- tableId를 url에서 정상적으로 가져오도록 수정
useParams을 통해 정상적으로 tableId를 가져오도록 수정
> [FIX] PostUserResponseType타입 수정, TableOverview에서 tableId를 url에서 정상적으로 가져오도록 수정

- package.json
- src/hooks/useFunnel.tsx
- src/page/TableComposition/TableComposition.test.tsx
- src/page/TableComposition/TableComposition.tsx
- src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
closed #91
- 입력된 테이블이 없을 시, 테이블 생성하기 버튼을 블럭 처리
- 토론주제를 정상적으로 서버로 보내도록 수정
테이블 생성하기 버튼을 블럭 처리
없음
> [FIX] QA에서 식별한 버그 해결 - 치코

- src/apis/apis.ts
- src/page/TableComposition/TableComposition.test.tsx
- src/page/TableComposition/TableComposition.tsx
- src/page/TableComposition/hook/useTableFrom.tsx
- src/page/TableListPage/components/Modal/CreateTableModal.tsx
- src/page/TableListPage/components/Modal/EditTableModal.tsx
- src/page/TableListPage/components/Table/Table.tsx
closed #103 
- util/formatting 에 있는 Formatting 메소드 이용
```ts
export const Formatting = {
formatSecondsToMinutes: (time: number) => {
const minutes = Math.floor(time / 60);
const seconds = time % 60;
return { minutes, seconds };
},
// Function that set all number to be have 2 digits (if time is 3, it will return 03)
formatTwoDigits: (num: number): string => {
return num.toString().padStart(2, '0');
},
};
```
- Formatting 메소드 적용한 Table 컴포넌트 코드
```ts
export default function Table({
id,
name,
type,
duration,
onDelete,
}: DebateTableWithDelete) {
const navigate = useNavigate();
const handleClick = () => {
navigate(`/overview/${id}`);
};
const { minutes, seconds } = Formatting.formatSecondsToMinutes(duration);
const [durationMinutes, durationSeconds] = [minutes, seconds].map( …
```
> [Refactor] 1차 UT에서 발생한 피드백 반영

- src/apis/axiosInstance.ts
Reverts debate-timer/debate-timer-fe#119
> [CHORE] "deploy: 임시 PR" 복구

- .github/workflows/deploy-storybook.yml
closed #134 
```
07:44:52.294 Retrieving git information
07:44:52.323 → ✖ Found only one commit
This typically means you have ran into one of the following scenarios:
- You've checked out a shallow copy of the Git repository, which actions/checkout@v2 does by default.
In order for Chromatic to correctly determine baseline commits, we need access to the full Git history graph.
With actions/checkout@v2, you can enable this by setting 'fetch-depth: 0'.
ℹ Read more at https://www.chromatic.com/docs/github-actions
- You've only made a single commit so far. 
Please make at least one additional commit in order for Chromatic to be able to detect what's changed. 
07:44:52.338 ✖ Failed to retrieve git information
✖ Found only one commit
This typically means you have ran into one of the following …
```
> [FIX] Storybook 배포 오류 수정

- .github/ISSUE_TEMPLATE/deploy-template.md
- .github/workflows/CI.yml
closed #136
- CI 타켓 브랜치를 추가
- 배포 이슈 템플릿 추가
> [CHORE] PROD 배포에 CI 추가

- .github/workflows/PR_Comment_Noti.yml
closed #162
```/noti```를 사용할 경우 에러가 발생하는 문제가 발생합니다.
- 불필요한 TITLE을 제거
- jq를 사용해 안전한 문자열 처리 (  body가 여러줄인 경우, Invalid format 오류가 발생할 수 있다합니다.)
> [CHORE] notify-discord-comment yml 수정

- .github/workflows/Auto_PR_Setting.yml
closed #164
케이티의 영입으로 인한 Auto_PR_Setting파일에 리뷰어 목록에 케이티를 추가하고자 한다.
멤버 추가로 추가적으로 변경이 필요한 부분이 또 있을까요?
> [CHORE] 새로운 FE 멤버 영입으로 인한 Auto_PR_Setting 수정

- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/ErrorPage.tsx
- src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
closed #183
main 브랜치 병합 및 prod 배포
> [DEPLOY] 배포

- .github/workflows/Issue_Noti.yml
- .github/workflows/PR_Comment_Noti.yml
- .storybook/preview-head.html
closed #220 
/.storybook/preview-head.html에 웹 폰트를 지정하여, 웹 폰트가 반영된 정확한 UI가 출력될 수 있게 수정했습니다.
저번에 수정하고 더 안 건들려고 했는데, 치코가 처음 작업했을 때처럼 PR 코멘트 내용 안 나오는 게 불편했습니다.
그래서 PR 코멘트의 내용이 함께 출력되도록 개선했어요.
이번에는 제발 문제 없기를 바랍니다...
UI에 웹 폰트가 잘 적용되어 있는 것을 볼 수 있다. localhost 환경이기 때문에, Chromatic에까지 적용될지는 배포하고 확인해야 할 듯.
없음
> [CHORE] 일부 개발 환경 개선 사항 적용

- src/page/TimerPage/TimerPage.tsx
closed #225
의회식 토론 타이머 토론 종료 시, overview url 이동 패턴 변경
> [FIX] 의회식 토론 타이머 토론 종료 시, overview url 이동 패턴 변경 

- src/page/CustomizeTimerPage/components/NormalTimer.tsx
- src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx
closed #269 
- #252 와의 일부 코드 오버랩으로 발생한 UI 깨짐 문제를 타이머 부분 UI 반응형으로 수정
- 폰트 특성상 콜론이 중앙에 위치하지 않아 콜론 위치 직접 조정
- 작은화면 타이머의 폰트 굵기 조정
사진 비교가 큰 의미가 없다고 판단되어 직접 테스트 해보시며 화면 크기에 따른 디자인 확인 부탁드립니다!
> [FIX] 반응형 타이머 깨진 UI 수정
